---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: dad-group-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: api
          image: registry.172.22.21.107.sslip.io/dad-group-5/api:v1.0.0
          env:
            - name: APP_ENV
              value: "local"
            - name: DB_DATABASE
              value: "project"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  namespace: dad-group-5
spec:
  ports:
    - port: 80
  selector:
    app: laravel-app
